name: Run Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        python -m backend.tests.test_activation_pipeline
        python -m backend.tests.test_active_stop_selection
        python -m backend.tests.test_mark_trade_filled
        python -m backend.tests.test_trade_manager
        python -m backend.tests.test_validation
        python -m backend.tests.test_volatility
